import { CRMState } from "@/lib/types";

export const initialCRMState: CRMState = {
  users: [
    {
      id: "user-maria",
      name: "Maria Tamm",
      email: "maria@atlascoach.ee",
      role: "coach",
      timezone: "Europe/Tallinn",
    },
    {
      id: "user-kertu",
      name: "Kertu Vaher",
      email: "kertu@atlascoach.ee",
      role: "coach",
      timezone: "Europe/Tallinn",
    },
  ],
  leads: [
    {
      id: "lead-kristi",
      fullName: "Kristi Saar",
      email: "kristi.saar@example.com",
      phone: "+372 5555 1101",
      source: "Instagram DM",
      status: "contacted",
      goal: "Postpartum strength rebuild and confidence in the gym",
      nextStep: "Book first assessment + solo trial",
      preferredLanguage: "et",
      createdAt: "2026-03-18T09:20:00.000Z",
      lastContactAt: "2026-03-23T15:10:00.000Z",
      notes:
        "Responds quickly in Estonian. Prefers morning sessions and wants simple food structure.",
    },
    {
      id: "lead-daniel",
      fullName: "Daniel Reed",
      email: "daniel.reed@example.com",
      phone: "+372 5555 4412",
      source: "Referral",
      status: "trial-booked",
      goal: "Fat loss, shoulder-friendly upper body strength, accountability",
      nextStep: "Send intake and confirm payment details",
      preferredLanguage: "en",
      createdAt: "2026-03-15T13:00:00.000Z",
      lastContactAt: "2026-03-22T17:00:00.000Z",
      notes: "Trial booked for March 27 at 18:00. Works late; prefers evening follow-ups.",
    },
  ],
  clients: [
    {
      id: "client-ava",
      fullName: "Ava Kask",
      email: "ava.kask@example.com",
      phone: "+372 5550 1818",
      gender: "female",
      preferredLanguage: "et",
      goals: ["Lower-body strength", "Energy management", "Waistline reduction"],
      tags: ["solo", "body analysis", "nutrition support"],
      joinedAt: "2026-01-09T08:00:00.000Z",
      consentStatus: "signed",
      healthFlags: [
        {
          title: "Knee tolerance",
          detail: "Deep knee flexion volume should build gradually.",
          severity: "attention",
        },
        {
          title: "Stress load",
          detail: "Poor sleep on work-travel weeks; keep recovery note visible.",
          severity: "info",
        },
      ],
      notes:
        "Prefers direct coaching, likes clear progression targets, appreciates recap emails in Estonian.",
      ownerId: "user-maria",
      avatarHue: 18,
    },
    {
      id: "client-marko",
      fullName: "Marko Lepp",
      email: "marko.lepp@example.com",
      phone: "+372 5566 7788",
      gender: "male",
      preferredLanguage: "en",
      goals: ["Mass gain", "Improve posture", "More structured weekly routine"],
      tags: ["duo", "office worker"],
      joinedAt: "2025-11-21T10:30:00.000Z",
      consentStatus: "signed",
      healthFlags: [
        {
          title: "Desk posture",
          detail: "Thoracic stiffness and occasional neck tightness.",
          severity: "info",
        },
      ],
      notes:
        "Trains with a friend once a week and has one extra solo accessory session every other week.",
      ownerId: "user-maria",
      avatarHue: 212,
    },
    {
      id: "client-liis",
      fullName: "Liis Oja",
      email: "liis.oja@example.com",
      phone: "+372 5344 2200",
      gender: "female",
      preferredLanguage: "et",
      goals: ["Build confidence in gym machines", "Core control", "General wellness"],
      tags: ["small group", "beginner"],
      joinedAt: "2026-02-04T14:15:00.000Z",
      consentStatus: "pending",
      healthFlags: [
        {
          title: "Beginner pace",
          detail: "Needs simple cues and steady tempo instead of fast circuits.",
          severity: "info",
        },
      ],
      notes: "Usually joins a 4-person evening micro-group.",
      ownerId: "user-kertu",
      avatarHue: 148,
    },
  ],
  packageTemplates: [
    {
      id: "pt-solo-1",
      name: "1 x Solo",
      sessionCount: 1,
      tier: "solo",
      maxParticipants: 1,
      durationMinutes: 60,
      price: 55,
      currency: "EUR",
    },
    {
      id: "pt-solo-3",
      name: "3 x Solo",
      sessionCount: 3,
      tier: "solo",
      maxParticipants: 1,
      durationMinutes: 60,
      price: 150,
      currency: "EUR",
    },
    {
      id: "pt-solo-7",
      name: "7 x Solo",
      sessionCount: 7,
      tier: "solo",
      maxParticipants: 1,
      durationMinutes: 60,
      price: 315,
      currency: "EUR",
    },
    {
      id: "pt-duo-1",
      name: "1 x Duo",
      sessionCount: 1,
      tier: "duo",
      maxParticipants: 2,
      durationMinutes: 60,
      price: 72,
      currency: "EUR",
    },
    {
      id: "pt-duo-3",
      name: "3 x Duo",
      sessionCount: 3,
      tier: "duo",
      maxParticipants: 2,
      durationMinutes: 60,
      price: 198,
      currency: "EUR",
    },
    {
      id: "pt-duo-7",
      name: "7 x Duo",
      sessionCount: 7,
      tier: "duo",
      maxParticipants: 2,
      durationMinutes: 60,
      price: 455,
      currency: "EUR",
    },
    {
      id: "pt-group-1",
      name: "1 x Small Group",
      sessionCount: 1,
      tier: "group",
      maxParticipants: 4,
      durationMinutes: 60,
      price: 28,
      currency: "EUR",
    },
    {
      id: "pt-group-3",
      name: "3 x Small Group",
      sessionCount: 3,
      tier: "group",
      maxParticipants: 4,
      durationMinutes: 60,
      price: 75,
      currency: "EUR",
    },
    {
      id: "pt-group-7",
      name: "7 x Small Group",
      sessionCount: 7,
      tier: "group",
      maxParticipants: 4,
      durationMinutes: 60,
      price: 168,
      currency: "EUR",
    },
  ],
  packagePurchases: [
    {
      id: "pkg-ava-7",
      clientId: "client-ava",
      templateId: "pt-solo-7",
      purchasedAt: "2026-03-01T09:00:00.000Z",
      startsAt: "2026-03-01T09:00:00.000Z",
      expiresAt: "2026-05-31T21:00:00.000Z",
      totalUnits: 7,
      usedUnits: 3,
      price: 315,
      paymentStatus: "paid",
      invoiceId: "inv-ava-7",
      notes: "Renewed after progress review.",
    },
    {
      id: "pkg-marko-3",
      clientId: "client-marko",
      templateId: "pt-duo-3",
      purchasedAt: "2026-03-10T12:00:00.000Z",
      startsAt: "2026-03-10T12:00:00.000Z",
      expiresAt: "2026-04-30T21:00:00.000Z",
      totalUnits: 3,
      usedUnits: 1,
      price: 198,
      paymentStatus: "partial",
      invoiceId: "inv-marko-3",
    },
    {
      id: "pkg-liis-7",
      clientId: "client-liis",
      templateId: "pt-group-7",
      purchasedAt: "2026-02-20T17:00:00.000Z",
      startsAt: "2026-02-20T17:00:00.000Z",
      expiresAt: "2026-04-20T21:00:00.000Z",
      totalUnits: 7,
      usedUnits: 4,
      price: 168,
      paymentStatus: "paid",
      invoiceId: "inv-liis-7",
    },
  ],
  sessions: [
    {
      id: "session-ava-0321",
      title: "Lower body rebuild",
      coachId: "user-maria",
      primaryClientId: "client-ava",
      clientIds: ["client-ava"],
      kind: "solo",
      startAt: "2026-03-21T08:00:00.000Z",
      endAt: "2026-03-21T09:00:00.000Z",
      location: "Atlas Studio A",
      status: "completed",
      packagePurchaseId: "pkg-ava-7",
      plannedWorkoutId: "pw-ava-0321",
      sessionWorkoutId: "sw-ava-0321",
      reminderAt: "2026-03-20T18:00:00.000Z",
      calendarSync: "synced",
      note: "Energy was low but technique stayed sharp.",
    },
    {
      id: "session-ava-0324",
      title: "Strength + confidence day",
      coachId: "user-maria",
      primaryClientId: "client-ava",
      clientIds: ["client-ava"],
      kind: "solo",
      startAt: "2026-03-24T08:00:00.000Z",
      endAt: "2026-03-24T09:00:00.000Z",
      location: "Atlas Studio A",
      status: "in-progress",
      packagePurchaseId: "pkg-ava-7",
      plannedWorkoutId: "pw-ava-0324",
      sessionWorkoutId: "sw-ava-0324",
      reminderAt: "2026-03-23T18:00:00.000Z",
      calendarSync: "synced",
      note: "Open from client profile before the session begins.",
    },
    {
      id: "session-marko-0326",
      title: "Duo upper body progression",
      coachId: "user-maria",
      primaryClientId: "client-marko",
      clientIds: ["client-marko"],
      kind: "duo",
      startAt: "2026-03-26T18:00:00.000Z",
      endAt: "2026-03-26T19:00:00.000Z",
      location: "Atlas Studio B",
      status: "planned",
      packagePurchaseId: "pkg-marko-3",
      plannedWorkoutId: "pw-marko-0326",
      sessionWorkoutId: "sw-marko-0326",
      reminderAt: "2026-03-25T16:00:00.000Z",
      calendarSync: "pending",
      note: "Need pair-friendly station flow.",
    },
    {
      id: "session-liis-0325",
      title: "Small group fundamentals",
      coachId: "user-kertu",
      primaryClientId: "client-liis",
      clientIds: ["client-liis"],
      kind: "group",
      startAt: "2026-03-25T17:30:00.000Z",
      endAt: "2026-03-25T18:30:00.000Z",
      location: "Atlas Studio C",
      status: "planned",
      packagePurchaseId: "pkg-liis-7",
      plannedWorkoutId: "pw-liis-0325",
      sessionWorkoutId: "sw-liis-0325",
      reminderAt: "2026-03-24T14:00:00.000Z",
      calendarSync: "manual",
    },
  ],
  plannedWorkouts: [
    {
      id: "pw-ava-0321",
      clientId: "client-ava",
      sessionId: "session-ava-0321",
      sourcePlanId: "wp-ava-strength",
      title: "Week 3 / Session A",
      objective: "Own stable split squat depth and build hinge confidence.",
      createdAt: "2026-03-20T13:00:00.000Z",
      exercises: [
        {
          id: "pex-ava-1",
          exerciseId: "ex-trapbar",
          name: "Trap bar deadlift",
          focus: "Power from floor",
          note: "Reset each rep.",
          sets: [
            { id: "ps-1", label: "1", reps: "6", weightKg: 52.5, rpe: 7 },
            { id: "ps-2", label: "2", reps: "6", weightKg: 52.5, rpe: 7 },
            { id: "ps-3", label: "3", reps: "6", weightKg: 55, rpe: 8 },
          ],
        },
        {
          id: "pex-ava-2",
          exerciseId: "ex-split-squat",
          name: "Rear-foot elevated split squat",
          note: "Shallow range if knee feels stiff.",
          sets: [
            { id: "ps-4", label: "1", reps: "8/side", weightKg: 12, rpe: 7 },
            { id: "ps-5", label: "2", reps: "8/side", weightKg: 12, rpe: 7 },
            { id: "ps-6", label: "3", reps: "8/side", weightKg: 14, rpe: 8 },
          ],
        },
      ],
    },
    {
      id: "pw-ava-0324",
      clientId: "client-ava",
      sessionId: "session-ava-0324",
      sourcePlanId: "wp-ava-strength",
      title: "Week 3 / Session B",
      objective: "Progress lower-body strength without knee irritation and finish with confident upper-body pushing.",
      createdAt: "2026-03-23T10:00:00.000Z",
      exercises: [
        {
          id: "pex-ava-3",
          exerciseId: "ex-trapbar",
          name: "Trap bar deadlift",
          focus: "Explosive lockout",
          note: "Brace before every rep.",
          sets: [
            { id: "ps-7", label: "1", reps: "5", weightKg: 57.5, rpe: 7 },
            { id: "ps-8", label: "2", reps: "5", weightKg: 57.5, rpe: 7.5 },
            { id: "ps-9", label: "3", reps: "5", weightKg: 60, rpe: 8 },
          ],
        },
        {
          id: "pex-ava-4",
          exerciseId: "ex-bench",
          name: "Dumbbell bench press",
          note: "Neutral wrist and steady 2-second lower.",
          sets: [
            { id: "ps-10", label: "1", reps: "10", weightKg: 14, tempo: "2-0-1" },
            { id: "ps-11", label: "2", reps: "10", weightKg: 14, tempo: "2-0-1" },
            { id: "ps-12", label: "3", reps: "8", weightKg: 16, rpe: 8 },
          ],
        },
        {
          id: "pex-ava-5",
          exerciseId: "ex-row",
          name: "Half-kneeling cable row",
          sets: [
            { id: "ps-13", label: "1", reps: "12/side", weightKg: 22 },
            { id: "ps-14", label: "2", reps: "12/side", weightKg: 24 },
            { id: "ps-15", label: "3", reps: "10/side", weightKg: 24, rpe: 8 },
          ],
        },
        {
          id: "pex-ava-6",
          exerciseId: "ex-bike",
          name: "Bike finisher",
          note: "6 rounds of 20 sec hard / 70 sec easy",
          sets: [{ id: "ps-16", label: "1", reps: "6 rounds", tempo: "20/70" }],
        },
      ],
    },
    {
      id: "pw-marko-0326",
      clientId: "client-marko",
      sessionId: "session-marko-0326",
      sourcePlanId: "wp-marko-mass",
      title: "Week 4 / Duo push-pull",
      objective: "Keep pairs moving while progressing pressing strength.",
      createdAt: "2026-03-24T07:30:00.000Z",
      exercises: [
        {
          id: "pex-marko-1",
          exerciseId: "ex-incline",
          name: "Incline dumbbell press",
          sets: [
            { id: "ps-17", label: "1", reps: "10", weightKg: 24 },
            { id: "ps-18", label: "2", reps: "10", weightKg: 24 },
            { id: "ps-19", label: "3", reps: "8", weightKg: 26 },
          ],
        },
        {
          id: "pex-marko-2",
          exerciseId: "ex-chest-supported-row",
          name: "Chest supported row",
          sets: [
            { id: "ps-20", label: "1", reps: "12", weightKg: 28 },
            { id: "ps-21", label: "2", reps: "12", weightKg: 28 },
            { id: "ps-22", label: "3", reps: "10", weightKg: 30 },
          ],
        },
      ],
    },
    {
      id: "pw-liis-0325",
      clientId: "client-liis",
      sessionId: "session-liis-0325",
      sourcePlanId: "wp-liis-foundations",
      title: "Group fundamentals / A",
      objective: "Machine confidence, smooth tempo, and easy breathing under load.",
      createdAt: "2026-03-24T08:15:00.000Z",
      exercises: [
        {
          id: "pex-liis-1",
          exerciseId: "ex-legpress",
          name: "Leg press",
          sets: [
            { id: "ps-23", label: "1", reps: "12", weightKg: 70 },
            { id: "ps-24", label: "2", reps: "12", weightKg: 70 },
            { id: "ps-25", label: "3", reps: "10", weightKg: 75 },
          ],
        },
        {
          id: "pex-liis-2",
          exerciseId: "ex-latpulldown",
          name: "Lat pulldown",
          sets: [
            { id: "ps-26", label: "1", reps: "12", weightKg: 27.5 },
            { id: "ps-27", label: "2", reps: "12", weightKg: 27.5 },
            { id: "ps-28", label: "3", reps: "10", weightKg: 30 },
          ],
        },
      ],
    },
  ],
  sessionWorkouts: [
    {
      id: "sw-ava-0321",
      sessionId: "session-ava-0321",
      title: "Lower body rebuild",
      status: "completed",
      coachNote:
        "Energy low initially, but confidence improved after first two sets. Knee stayed calm with controlled descent.",
      athleteFacingNote:
        "Strong hinge quality today. Split squat depth improved and knee tolerance stayed good.",
      updatedAt: "2026-03-21T09:02:00.000Z",
      exercises: [
        {
          id: "sex-ava-1",
          plannedExerciseId: "pex-ava-1",
          exerciseId: "ex-trapbar",
          name: "Trap bar deadlift",
          status: "completed",
          sets: [
            {
              id: "set-1",
              label: "1",
              targetReps: "6",
              actualReps: "6",
              targetWeightKg: 52.5,
              actualWeightKg: 52.5,
              rpe: 7,
              completed: true,
            },
            {
              id: "set-2",
              label: "2",
              targetReps: "6",
              actualReps: "6",
              targetWeightKg: 52.5,
              actualWeightKg: 52.5,
              rpe: 7,
              completed: true,
            },
            {
              id: "set-3",
              label: "3",
              targetReps: "6",
              actualReps: "6",
              targetWeightKg: 55,
              actualWeightKg: 55,
              rpe: 8,
              completed: true,
            },
          ],
        },
        {
          id: "sex-ava-2",
          plannedExerciseId: "pex-ava-2",
          exerciseId: "ex-split-squat",
          name: "Rear-foot elevated split squat",
          status: "modified",
          note: "Reduced depth on left side for first set.",
          sets: [
            {
              id: "set-4",
              label: "1",
              targetReps: "8/side",
              actualReps: "8/side",
              targetWeightKg: 12,
              actualWeightKg: 12,
              rpe: 7,
              completed: true,
            },
            {
              id: "set-5",
              label: "2",
              targetReps: "8/side",
              actualReps: "8/side",
              targetWeightKg: 12,
              actualWeightKg: 12,
              rpe: 7,
              completed: true,
            },
            {
              id: "set-6",
              label: "3",
              targetReps: "8/side",
              actualReps: "6/side",
              targetWeightKg: 14,
              actualWeightKg: 12,
              rpe: 8,
              completed: true,
            },
          ],
        },
      ],
    },
    {
      id: "sw-ava-0324",
      sessionId: "session-ava-0324",
      title: "Strength + confidence day",
      status: "live",
      coachNote:
        "Start from the plan and adjust if knee discomfort or fatigue shows up. Use clear confidence cues.",
      athleteFacingNote: "",
      updatedAt: "2026-03-24T07:55:00.000Z",
      exercises: [
        {
          id: "sex-ava-3",
          plannedExerciseId: "pex-ava-3",
          exerciseId: "ex-trapbar",
          name: "Trap bar deadlift",
          status: "planned",
          sets: [
            {
              id: "set-7",
              label: "1",
              targetReps: "5",
              actualReps: "5",
              targetWeightKg: 57.5,
              actualWeightKg: 57.5,
              rpe: 7,
              completed: false,
            },
            {
              id: "set-8",
              label: "2",
              targetReps: "5",
              actualReps: "5",
              targetWeightKg: 57.5,
              actualWeightKg: 57.5,
              rpe: 7.5,
              completed: false,
            },
            {
              id: "set-9",
              label: "3",
              targetReps: "5",
              actualReps: "5",
              targetWeightKg: 60,
              actualWeightKg: 60,
              rpe: 8,
              completed: false,
            },
          ],
        },
        {
          id: "sex-ava-4",
          plannedExerciseId: "pex-ava-4",
          exerciseId: "ex-bench",
          name: "Dumbbell bench press",
          status: "planned",
          sets: [
            {
              id: "set-10",
              label: "1",
              targetReps: "10",
              actualReps: "10",
              targetWeightKg: 14,
              actualWeightKg: 14,
              tempo: "2-0-1",
              completed: false,
            },
            {
              id: "set-11",
              label: "2",
              targetReps: "10",
              actualReps: "10",
              targetWeightKg: 14,
              actualWeightKg: 14,
              tempo: "2-0-1",
              completed: false,
            },
            {
              id: "set-12",
              label: "3",
              targetReps: "8",
              actualReps: "8",
              targetWeightKg: 16,
              actualWeightKg: 16,
              rpe: 8,
              completed: false,
            },
          ],
        },
        {
          id: "sex-ava-5",
          plannedExerciseId: "pex-ava-5",
          exerciseId: "ex-row",
          name: "Half-kneeling cable row",
          status: "planned",
          sets: [
            {
              id: "set-13",
              label: "1",
              targetReps: "12/side",
              actualReps: "12/side",
              targetWeightKg: 22,
              actualWeightKg: 22,
              completed: false,
            },
            {
              id: "set-14",
              label: "2",
              targetReps: "12/side",
              actualReps: "12/side",
              targetWeightKg: 24,
              actualWeightKg: 24,
              completed: false,
            },
            {
              id: "set-15",
              label: "3",
              targetReps: "10/side",
              actualReps: "10/side",
              targetWeightKg: 24,
              actualWeightKg: 24,
              rpe: 8,
              completed: false,
            },
          ],
        },
        {
          id: "sex-ava-6",
          plannedExerciseId: "pex-ava-6",
          exerciseId: "ex-bike",
          name: "Bike finisher",
          status: "planned",
          sets: [
            {
              id: "set-16",
              label: "1",
              targetReps: "6 rounds",
              actualReps: "6 rounds",
              tempo: "20/70",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sw-marko-0326",
      sessionId: "session-marko-0326",
      title: "Duo upper body progression",
      status: "draft",
      coachNote: "Keep pair rhythm smooth. Add face pulls if the second athlete finishes early.",
      athleteFacingNote: "",
      updatedAt: "2026-03-24T07:40:00.000Z",
      exercises: [
        {
          id: "sex-marko-1",
          plannedExerciseId: "pex-marko-1",
          exerciseId: "ex-incline",
          name: "Incline dumbbell press",
          status: "planned",
          sets: [
            {
              id: "set-17",
              label: "1",
              targetReps: "10",
              actualReps: "10",
              targetWeightKg: 24,
              actualWeightKg: 24,
              completed: false,
            },
            {
              id: "set-18",
              label: "2",
              targetReps: "10",
              actualReps: "10",
              targetWeightKg: 24,
              actualWeightKg: 24,
              completed: false,
            },
            {
              id: "set-19",
              label: "3",
              targetReps: "8",
              actualReps: "8",
              targetWeightKg: 26,
              actualWeightKg: 26,
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sw-liis-0325",
      sessionId: "session-liis-0325",
      title: "Small group fundamentals",
      status: "draft",
      coachNote: "Use machine setup teaching moments and keep the floor calm.",
      athleteFacingNote: "",
      updatedAt: "2026-03-24T08:20:00.000Z",
      exercises: [
        {
          id: "sex-liis-1",
          plannedExerciseId: "pex-liis-1",
          exerciseId: "ex-legpress",
          name: "Leg press",
          status: "planned",
          sets: [
            {
              id: "set-20",
              label: "1",
              targetReps: "12",
              actualReps: "12",
              targetWeightKg: 70,
              actualWeightKg: 70,
              completed: false,
            },
            {
              id: "set-21",
              label: "2",
              targetReps: "12",
              actualReps: "12",
              targetWeightKg: 70,
              actualWeightKg: 70,
              completed: false,
            },
            {
              id: "set-22",
              label: "3",
              targetReps: "10",
              actualReps: "10",
              targetWeightKg: 75,
              actualWeightKg: 75,
              completed: false,
            },
          ],
        },
      ],
    },
  ],
  bodyAssessments: [
    {
      id: "ba-ava-0301",
      clientId: "client-ava",
      recordedAt: "2026-03-01T08:30:00.000Z",
      recordedBy: "user-maria",
      notes: "Improved hydration this week; waist down slightly despite travel.",
      metrics: [
        { id: "metric-1", label: "Weight", unit: "kg", value: 68.4 },
        { id: "metric-2", label: "Body fat", unit: "%", value: 28.2 },
        { id: "metric-3", label: "Waist", unit: "cm", value: 77.5 },
      ],
    },
    {
      id: "ba-ava-0322",
      clientId: "client-ava",
      recordedAt: "2026-03-22T08:30:00.000Z",
      recordedBy: "user-maria",
      notes: "Lean mass steady, waist slightly down, reports more stable energy.",
      metrics: [
        { id: "metric-4", label: "Weight", unit: "kg", value: 67.9 },
        { id: "metric-5", label: "Body fat", unit: "%", value: 27.6 },
        { id: "metric-6", label: "Waist", unit: "cm", value: 76.8 },
      ],
    },
    {
      id: "ba-marko-0312",
      clientId: "client-marko",
      recordedAt: "2026-03-12T18:15:00.000Z",
      recordedBy: "user-maria",
      notes: "Weight trending upward as planned. Appetite still inconsistent.",
      metrics: [
        { id: "metric-7", label: "Weight", unit: "kg", value: 81.1 },
        { id: "metric-8", label: "Chest", unit: "cm", value: 104 },
        { id: "metric-9", label: "Upper arm", unit: "cm", value: 35.5 },
      ],
    },
  ],
  workoutPlans: [
    {
      id: "wp-ava-strength",
      clientId: "client-ava",
      title: "Lower body confidence block",
      status: "active",
      goal: "Build strength while keeping knee response calm and confidence high.",
      focusAreas: ["Hinge strength", "Single-leg control", "Progressive pushing"],
      sessionPattern: ["Day A: hinge + split squat", "Day B: strength + press"],
      activeFrom: "2026-03-01T00:00:00.000Z",
      createdAt: "2026-02-27T11:00:00.000Z",
      updatedAt: "2026-03-23T10:00:00.000Z",
      origin: "ai",
    },
    {
      id: "wp-marko-mass",
      clientId: "client-marko",
      title: "Mass phase / upper bias",
      status: "active",
      goal: "Drive chest and back volume while keeping weekly structure realistic.",
      focusAreas: ["Upper pushing", "Upper pulling", "Recovery habits"],
      sessionPattern: ["Duo push-pull", "Optional solo accessory"],
      activeFrom: "2026-03-10T00:00:00.000Z",
      createdAt: "2026-03-08T15:00:00.000Z",
      updatedAt: "2026-03-24T07:30:00.000Z",
      origin: "coach",
    },
    {
      id: "wp-liis-foundations",
      clientId: "client-liis",
      title: "Foundations and machine fluency",
      status: "active",
      goal: "Make gym equipment feel predictable and approachable.",
      focusAreas: ["Machine confidence", "Tempo control", "Core posture"],
      sessionPattern: ["Group fundamentals A", "Group fundamentals B"],
      activeFrom: "2026-03-15T00:00:00.000Z",
      createdAt: "2026-03-14T17:00:00.000Z",
      updatedAt: "2026-03-24T08:15:00.000Z",
      origin: "coach",
    },
  ],
  nutritionPlans: [
    {
      id: "np-ava",
      clientId: "client-ava",
      title: "Travel-proof fat loss support",
      status: "active",
      calories: 1910,
      proteinGrams: 135,
      carbsGrams: 185,
      fatsGrams: 62,
      hydrationLiters: 2.6,
      principles: [
        "Protein at every meal",
        "Portable breakfast option for travel days",
        "1 planned flexible meal on weekends",
      ],
      createdAt: "2026-03-02T09:00:00.000Z",
      updatedAt: "2026-03-22T09:00:00.000Z",
      origin: "ai",
    },
    {
      id: "np-marko",
      clientId: "client-marko",
      title: "Mass support base plan",
      status: "active",
      calories: 3080,
      proteinGrams: 175,
      carbsGrams: 390,
      fatsGrams: 88,
      hydrationLiters: 3.1,
      principles: [
        "Pre-packed afternoon calories",
        "Protein + carbs after duo training",
        "Weekend meal prep fallback",
      ],
      createdAt: "2026-03-12T12:00:00.000Z",
      updatedAt: "2026-03-22T12:00:00.000Z",
      origin: "coach",
    },
  ],
  exerciseLibrary: [
    { id: "ex-trapbar", name: "Trap bar deadlift", category: "Lower body", primaryUnit: "kg" },
    { id: "ex-split-squat", name: "Rear-foot elevated split squat", category: "Lower body", primaryUnit: "kg" },
    { id: "ex-bench", name: "Dumbbell bench press", category: "Upper body", primaryUnit: "kg" },
    { id: "ex-row", name: "Half-kneeling cable row", category: "Upper body", primaryUnit: "kg" },
    { id: "ex-bike", name: "Bike finisher", category: "Conditioning", primaryUnit: "minutes" },
    { id: "ex-incline", name: "Incline dumbbell press", category: "Upper body", primaryUnit: "kg" },
    { id: "ex-chest-supported-row", name: "Chest supported row", category: "Upper body", primaryUnit: "kg" },
    { id: "ex-legpress", name: "Leg press", category: "Lower body", primaryUnit: "kg" },
    { id: "ex-latpulldown", name: "Lat pulldown", category: "Upper body", primaryUnit: "kg" },
  ],
  emailThreads: [
    {
      id: "thread-ava-progress",
      clientId: "client-ava",
      subject: "Weekly progress recap",
      source: "outlook",
      updatedAt: "2026-03-22T16:30:00.000Z",
    },
    {
      id: "thread-marko-checkin",
      clientId: "client-marko",
      subject: "Nutrition adherence and next week",
      source: "outlook",
      updatedAt: "2026-03-20T19:05:00.000Z",
    },
  ],
  emailMessages: [
    {
      id: "msg-ava-1",
      threadId: "thread-ava-progress",
      clientId: "client-ava",
      direction: "outbound",
      subject: "Weekly progress recap",
      body:
        "Great work this week. Hinge confidence is clearly improving and your waist trend is heading in the right direction.",
      sentAt: "2026-03-22T16:30:00.000Z",
    },
    {
      id: "msg-ava-2",
      threadId: "thread-ava-progress",
      clientId: "client-ava",
      direction: "inbound",
      subject: "Re: Weekly progress recap",
      body: "Thank you. The travel breakfast idea helped a lot.",
      sentAt: "2026-03-22T19:15:00.000Z",
    },
    {
      id: "msg-marko-1",
      threadId: "thread-marko-checkin",
      clientId: "client-marko",
      direction: "outbound",
      subject: "Nutrition adherence and next week",
      body:
        "Please prioritize the afternoon calories this week. We’ll keep the duo session structure simple and progressive.",
      sentAt: "2026-03-20T19:05:00.000Z",
    },
  ],
  reminders: [
    {
      id: "rem-ava-0324",
      clientId: "client-ava",
      sessionId: "session-ava-0324",
      title: "24h reminder",
      dueAt: "2026-03-23T18:00:00.000Z",
      channel: "calendar",
      status: "sent",
    },
    {
      id: "rem-marko-0326",
      clientId: "client-marko",
      sessionId: "session-marko-0326",
      title: "24h reminder",
      dueAt: "2026-03-25T16:00:00.000Z",
      channel: "email",
      status: "scheduled",
    },
    {
      id: "rem-liis-consent",
      clientId: "client-liis",
      title: "Send consent follow-up",
      dueAt: "2026-03-24T12:00:00.000Z",
      channel: "email",
      status: "scheduled",
    },
  ],
  invoiceRecords: [
    {
      id: "inv-ava-7",
      clientId: "client-ava",
      packagePurchaseId: "pkg-ava-7",
      issuedAt: "2026-03-01T09:00:00.000Z",
      dueAt: "2026-03-03T21:00:00.000Z",
      amount: 315,
      currency: "EUR",
      paymentStatus: "paid",
    },
    {
      id: "inv-marko-3",
      clientId: "client-marko",
      packagePurchaseId: "pkg-marko-3",
      issuedAt: "2026-03-10T12:00:00.000Z",
      dueAt: "2026-03-15T21:00:00.000Z",
      amount: 198,
      currency: "EUR",
      paymentStatus: "partial",
    },
    {
      id: "inv-liis-7",
      clientId: "client-liis",
      packagePurchaseId: "pkg-liis-7",
      issuedAt: "2026-02-20T17:00:00.000Z",
      dueAt: "2026-02-25T21:00:00.000Z",
      amount: 168,
      currency: "EUR",
      paymentStatus: "paid",
    },
  ],
  paymentRecords: [
    {
      id: "pay-ava-1",
      clientId: "client-ava",
      invoiceId: "inv-ava-7",
      paidAt: "2026-03-02T10:00:00.000Z",
      amount: 315,
      currency: "EUR",
      method: "bank transfer",
    },
    {
      id: "pay-marko-1",
      clientId: "client-marko",
      invoiceId: "inv-marko-3",
      paidAt: "2026-03-11T09:00:00.000Z",
      amount: 99,
      currency: "EUR",
      method: "card",
    },
    {
      id: "pay-liis-1",
      clientId: "client-liis",
      invoiceId: "inv-liis-7",
      paidAt: "2026-02-21T08:00:00.000Z",
      amount: 168,
      currency: "EUR",
      method: "bank transfer",
    },
  ],
  activityEvents: [
    {
      id: "act-1",
      actor: "Maria Tamm",
      clientId: "client-ava",
      type: "session.updated",
      detail: "Opened live workout log for Ava Kask.",
      createdAt: "2026-03-24T07:57:00.000Z",
    },
    {
      id: "act-2",
      actor: "System",
      clientId: "client-marko",
      type: "reminder.queued",
      detail: "Queued 24h reminder for March 26 duo session.",
      createdAt: "2026-03-24T07:40:00.000Z",
    },
    {
      id: "act-3",
      actor: "Maria Tamm",
      clientId: "client-ava",
      type: "assessment.saved",
      detail: "Saved new body assessment with waist and body-fat updates.",
      createdAt: "2026-03-22T08:45:00.000Z",
    },
    {
      id: "act-4",
      actor: "Maria Tamm",
      clientId: "client-ava",
      type: "email.sent",
      detail: "Sent weekly progress recap via Outlook thread.",
      createdAt: "2026-03-22T16:30:00.000Z",
    },
  ],
  aiDrafts: [
    {
      id: "draft-ava-summary-0321",
      type: "workout-summary",
      clientId: "client-ava",
      sessionId: "session-ava-0321",
      title: "Post-session recap",
      subject: "Quick recap from today’s session",
      body:
        "You handled the hinge work well today and your split squat control improved even with a cautious range on the last set.",
      internalNote: "Keep depth progression gradual next time.",
      locale: "en",
      status: "sent",
      createdAt: "2026-03-21T09:05:00.000Z",
      updatedAt: "2026-03-21T09:08:00.000Z",
      model: "gpt-fallback-draft",
      promptType: "workout-summary",
      sources: ["session-ava-0321", "ba-ava-0301"],
    },
  ],
};
